---
title: "My personal website"
description: "A personal website to host my articles and projects regarding Data Science."
date: 2022-09-20
lang: en
---

My first project is the website where you are reading those lines. Maintaining a blog at the same time you are learning about Data Science is considered a good practice. You reiterate what you are learning and improve your ability to present your work to an audience. While an already-established platform like Medium or WordPress is an easy choice, I wanted to create something from scratch to test my Python programming skills.

I was fortunate to take a series of online classes about Web Development using HTML, CSS, and JavaScript and the python framework Flask on a Greek MOOC platform called Mathesis. [`Flask`](https://flask.palletsprojects.com) is a microweb framework designed to help you create the backend of a website with as few computing resources as possible. It supports extensions that can add new features according to your needs. Well-known applications like Pinterest and LinkedIn are using Flask. For those speaking English, I recommend Miguel Grinberg’s book `Flask Web Development: Developing Web Applications with Python` and his blog <https://blog.miguelgrinberg.com>, both excellent sources of reference for anything relating to the Flask framework. A second book that will help you master the framework is `Mastering Flask Web Development` by Daniel Gaspar and Jack Stouffer on Packt.

With the extension `Flask-Babel`, the site can support multiple languages. On my first website iteration, I also used Flask-CKEditor. CKEditor is a rich text editor which enables writing content directly inside of web pages or online applications used by many blogs and note-taking apps. Though CKEditor is a powerful editor, I quickly understand that I needed something oriented specifically to data science. When you start learning about Data Science you usually also learn to use Jupyter Notebooks. Notebooks are a great tool to quickly try new ideas, reiterate and present code along with charts and your conclusions. However, Notebook’s format is not well suited for a published article or a report. That’s what Quarto is coming to solve.

[Quarto](https://quarto.org) is an open-source scientific and technical publishing system built on Pandoc. It can be used with R, Python, Julia, and Observable JS and integrated with VS Code, Jupyter, R Studio, or even a simple text editor. You can publish high-quality articles, reports, presentations, and books by transforming markdown files or Jupyter Notebooks to HTML, pdf, Word Documents, epub books, etc. With Quarto, you can also create a static website or blog and publish it on GitHub Pages, Netlify, RStudio Connect, or any other static-hosting service. You don’t even need to learn Flask, maybe a little HTML and CSS, just enough to change the default bootstrap templates to your liking. In addition to the documentation there are two great articles about blogging with Quarto, the [first one](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html) is taking about setting up your blog and the [second one](https://marioangst.com/en/blog/posts/multi-language-quarto/) about dual language support.

So I decided to combine my original Flask website with a static one on Github. The first one is hosted on pythonanywhere, presenting the blog index and portfolio index, a contact, and an about page. The second one is responsible for the article and project pages. I create them with either markdown or Jupyter, upload them on Github, and list them on my original site with a title, a description, a photo, and a link.